# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  docs-build:
    branches:
      only:
        - master
    docker:
      - image: circleci/ruby:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build docs
          command: bundle exec middleman build --clean
      - persist_to_workspace:
          root: build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: html
      - run:
          name: Disable jekyll builds
          command: touch html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "it@jobylon.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "59:ad:fd:64:71:eb:81:01:6a:d7:1a:c9:0c:19:39:af"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist html


workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy
        requires:
          - docs-build
        filters:
          branches:
            only: master